var data = {
  wordCountMapping_goal_one:
  {
  "european":   6562,
  "international":   3479,
  "members":   3150,
  "research":   3052,
  "europe":   3047,
  "development":   3031,
  "services":   2486,
  "national":   2402,
  "social":   2266,
  "association":   2187,
  "industry":   2185,
  "information":   1998,
  "business":   1986,
  "promote":   1916,
  "policy":   1855,
  "support":   1802,
  "activities":   1725,
  "organisations":   1675,
  "companies":   1644,
  "institutions":   1639,
  "global":   1575,
  "work":   1519,
  "europa":   1504,
  "countries":   1455,
  "management":   1437,
  "world":   1418,
  "people":   1417,
  "sector":   1406,
  "network":   1382,
  "interests":   1360,
  "well":   1343,
  "energy":   1342,
  "education":   1312,
  "member":   1307,
  "issues":   1305,
  "mission":   1279,
  "sustainable":   1275,
  "health":   1269,
  "organisation":   1247,
  "level":   1242,
  "provide":   1242,
  "society":   1217,
  "market":   1193,
  "products":   1165,
  "associations":   1123,
  "economic":   1119,
  "rights":   1107,
  "projects":   1063,
  "local":   1062,
  "trade":   1062,
  "company":   1053,
  "new":   1023,
  "union":   1011,
  "solutions":   1003,
  "cooperation":    970,
  "group":    963,
  "quality":    962,
  "knowledge":    953,
  "working":    953,
  "including":    951,
  "professional":    946,
  "environment":    936,
  "innovation":    934,
  "technology":    928,
  "environmental":    892,
  "can":    879,
  "regional":    879,
  "across":    856,
  "leading":    850,
  "financial":    848,
  "based":    846,
  "within":    839,
  "use":    819,
  "training":    809,
  "human":    804,
  "one":    794,
  "standards":    789,
  "develop":    788,
  "main":    783,
  "protection":    781,
  "political":    759,
  "together":    759,
  "private":    754,
  "service":    753,
  "providing":    740,
  "technical":    735,
  "independent":    733,
  "scientific":    732,
  "clients":    731,
  "represents":    723,
  "policies":    710,
  "law":    706,
  "promoting":    705,
  "community":    702
  },
  wordsList_goal_one:
  [
  "european",
  "international",
  "members",
  "research",
  "europe",
  "development",
  "public",
  "services",
  "national",
  "social",
  "association",
  "industry",
  "information",
  "business",
  "promote",
  "policy",
  "support",
  "activities",
  "organisations",
  "companies",
  "institutions",
  "global",
  "work",
  "countries",
  "management",
  "world",
  "people",
  "sector",
  "network",
  "interests",
  "well",
  "energy",
  "education",
  "member",
  "issues",
  "mission",
  "sustainable",
  "health",
  "organisation",
  "level",
  "provide",
  "society",
  "market",
  "products",
  "associations",
  "economic",
  "rights",
  "projects",
  "local",
  "trade",
  "company",
  "new",
  "ρ�",
  "union",
  "solutions",
  "π�",
  "σ�",
  "cooperation",
  "group",
  "quality",
  "knowledge",
  "working",
  "including",
  "professional",
  "environment",
  "innovation",
  "technology",
  "environmental",
  "can",
  "regional",
  "across",
  "leading",
  "financial",
  "based",
  "σ�",
  "within",
  "р�",
  "use",
  "training",
  "human",
  "one",
  "standards",
  "develop",
  "main",
  "protection",
  "political",
  "together",
  "private",
  "service",
  "providing",
  "technical",
  "independent",
  "scientific",
  "clients",
  "represents",
  "policies",
  "law",
  "promoting",
  "community",
  ],
  wordCountMapping_activity_one:
  {
  "european":   3381,
  "directive":   3061,
  "policy":   2721,
  "energy":   2106,
  "regulation":   2071,
  "market":   1706,
  "policies":   1143,
  "digital":   1128,
  "development":   1099,
  "protection":   1042,
  "union":   1026,
  "trade":   1015,
  "health":    989,
  "europe":    976,
  "social":    953,
  "research":    936,
  "initiatives":    881,
  "strategy":    876,
  "single":    874,
  "rights":    810,
  "data":    807,
  "legislation":    756,
  "framework":    755,
  "commission":    751,
  "public":    745,
  "economy":    742,
  "europa":    720,
  "innovation":    716,
  "horizon":    707,
  "services":    707,
  "related":    701,
  "transport":    697,
  "climate":    684,
  "food":    683,
  "education":    672,
  "issues":    656,
  "financial":    653,
  "council":    648,
  "implementation":    637,
  "safety":    584,
  "parliament":    579,
  "environment":    576,
  "security":    570,
  "package":    550,
  "agenda":    539,
  "international":    521,
  "activities":    511,
  "circular":    500,
  "information":    495,
  "waste":    492,
  "action":    481,
  "work":    477,
  "including":    475,
  "products":    470,
  "programme":    451,
  "ttip":    449,
  "environmental":    439,
  "investment":    433,
  "plan":    431,
  "review":    420,
  "sustainable":    415,
  "markets":    414,
  "copyright":    410,
  "efficiency":    392,
  "initiative":    392,
  "general":    386,
  "law":    385,
  "human":    376,
  "member":    376,
  "new":    373,
  "consumer":    371,
  "sector":    369,
  "following":    364,
  "affairs":    359,
  "areas":    347,
  "capital":    347,
  "proposal":    347,
  "legislative":    345,
  "industry":    344,
  "reach":    340,
  "change":    339,
  "common":    338,
  "group":    336,
  "consultation":    334,
  "internal":    333,
  "business":    332,
  "access":    331,
  "economic":    331,
  "regulations":    331,
  "institutions":    329,
  "etc":    328,
  "management":    324,
  "pola":    321,
  "water":    308,
  "national":    307,
  "working":    304,
  "cooperation":    301,
  "competition":    299,
  "regional":    299
  },
  wordsList_activity_one:
  [
  "european",
  "directive",
  "policy",
  "energy",
  "regulation",
  "market",
  "policies",
  "digital",
  "development",
  "protection",
  "union",
  "trade",
  "health",
  "europe",
  "social",
  "research",
  "initiatives",
  "strategy",
  "single",
  "rights",
  "data",
  "legislation",
  "framework",
  "commission",
  "public",
  "economy",
  "europa",
  "innovation",
  "horizon",
  "services",
  "related",
  "transport",
  "climate",
  "food",
  "education",
  "issues",
  "financial",
  "council",
  "implementation",
  "safety",
  "parliament",
  "environment",
  "security",
  "package",
  "agenda",
  "international",
  "activities",
  "circular",
  "information",
  "waste",
  "action",
  "work",
  "including",
  "products",
  "programme",
  "ttip",
  "environmental",
  "investment",
  "plan",
  "review",
  "sustainable",
  "markets",
  "copyright",
  "efficiency",
  "initiative",
  "general",
  "law",
  "human",
  "member",
  "new",
  "consumer",
  "sector",
  "following",
  "affairs",
  "areas",
  "capital",
  "proposal",
  "legislative",
  "industry",
  "reach",
  "change",
  "common",
  "group",
  "consultation",
  "internal",
  "business",
  "access",
  "economic",
  "regulations",
  "institutions",
  "etc",
  "management",
  "Ï€Î",
  "pola",
  "water",
  "national",
  "working",
  "cooperation",
  "competition",
  "regional"
  ],
  wordCountMapping_both_one:
  {
  "european":   9943,
  "policy":   4576,
  "development":   4130,
  "europe":   4023,
  "international":   4000,
  "research":   3988,
  "energy":   3448,
  "members":   3446,
  "public":   3297,
  "social":   3219,
  "services":   3193,
  "directive":   3124,
  "market":   2899,
  "national":   2709,
  "industry":   2529,
  "information":   2493,
  "association":   2346,
  "business":   2318,
  "regulation":   2286,
  "health":   2258,
  "activities":   2236,
  "europa":   2224,
  "support":   2097,
  "trade":   2077,
  "promote":   2048,
  "union":   2037,
  "work":   1996,
  "education":   1984,
  "institutions":   1968,
  "issues":   1961,
  "rights":   1917,
  "policies":   1853,
  "protection":   1823,
  "organisations":   1812,
  "global":   1781,
  "sector":   1775,
  "management":   1761,
  "companies":   1754,
  "sustainable":   1690,
  "member":   1683,
  "countries":   1682,
  "innovation":   1650,
  "network":   1642,
  "products":   1635,
  "well":   1588,
  "digital":   1585,
  "people":   1564,
  "world":   1514,
  "environment":   1512,
  "level":   1505,
  "financial":   1501,
  "society":   1487,
  "interests":   1468,
  "economic":   1450,
  "including":   1426,
  "data":   1421,
  "organisation":   1408,
  "new":   1396,
  "transport":   1368,
  "related":   1361,
  "projects":   1350,
  "provide":   1344,
  "food":   1336,
  "environmental":   1331,
  "mission":   1328,
  "group":   1299,
  "initiatives":   1294,
  "cooperation":   1271,
  "commission":   1263,
  "working":   1257,
  "economy":   1250,
  "quality":   1234,
  "legislation":   1207,
  "strategy":   1207,
  "local":   1198,
  "associations":   1192,
  "human":   1180,
  "regional":   1178,
  "company":   1150,
  "technology":   1148,
  "safety":   1142,
  "framework":   1130,
  "implementation":   1127,
  "council":   1117,
  "professional":   1111,
  "law":   1091,
  "use":   1085,
  "solutions":   1066,
  "training":   1057,
  "knowledge":   1051,
  "climate":   1050,
  "areas":   1045,
  "security":   1038,
  "within":   1036,
  "main":   1028,
  "general":   1023 
  },
  wordsList_both_one:
  [
  "european",
  "policy",
  "development",
  "europe",
  "international",
  "research",
  "energy",
  "members",
  "public",
  "social",
  "services",
  "directive",
  "market",
  "national",
  "industry",
  "information",
  "association",
  "business",
  "regulation",
  "health",
  "activities",
  "europa",
  "support",
  "trade",
  "promote",
  "union",
  "work",
  "education",
  "institutions",
  "issues",
  "rights",
  "policies",
  "protection",
  "organisations",
  "global",
  "sector",
  "management",
  "companies",
  "sustainable",
  "member",
  "countries",
  "innovation",
  "network",
  "products",
  "well",
  "digital",
  "people",
  "world",
  "environment",
  "level",
  "financial",
  "society",
  "interests",
  "economic",
  "including",
  "data",
  "organisation",
  "new",
  "transport",
  "related",
  "projects",
  "provide",
  "food",
  "environmental",
  "mission",
  "group",
  "initiatives",
  "cooperation",
  "commission",
  "working",
  "economy",
  "quality",
  "legislation",
  "strategy",
  "local",
  "associations",
  "human",
  "regional",
  "company",
  "technology",
  "safety",
  "framework",
  "implementation",
  "council",
  "professional",
  "law",
  "use",
  "solutions",
  "training",
  "knowledge",
  "climate",
  "areas",
  "security",
  "within",
  "main",
  "general" 
  ],
  wordCountMapping_goal_two:
  {

  },
  wordsList_goal_two:
  [

  ],
  wordCountMapping_activity_two:
  {

  },

  wordsList_activity_two:
  [

  ],
  wordCountMapping_both_two:
  {

  },

  wordsList_both_two:
  [

  ],
}