var data = {
  wordCountMapping_goal_one:
  {
  "european":   6562,
  "international":   3479,
  "members":   3150,
  "research":   3052,
  "europe":   3047,
  "development":   3031,
  "services":   2486,
  "national":   2402,
  "social":   2266,
  "association":   2187,
  "industry":   2185,
  "information":   1998,
  "business":   1986,
  "promote":   1916,
  "policy":   1855,
  "support":   1802,
  "activities":   1725,
  "organisations":   1675,
  "companies":   1644,
  "institutions":   1639,
  "global":   1575,
  "work":   1519,
  "europa":   1504,
  "countries":   1455,
  "management":   1437,
  "world":   1418,
  "people":   1417,
  "sector":   1406,
  "network":   1382,
  "interests":   1360,
  "well":   1343,
  "energy":   1342,
  "education":   1312,
  "member":   1307,
  "issues":   1305,
  "mission":   1279,
  "sustainable":   1275,
  "health":   1269,
  "organisation":   1247,
  "level":   1242,
  "provide":   1242,
  "society":   1217,
  "market":   1193,
  "products":   1165,
  "associations":   1123,
  "economic":   1119,
  "rights":   1107,
  "projects":   1063,
  "local":   1062,
  "trade":   1062,
  "company":   1053,
  "new":   1023,
  "union":   1011,
  "solutions":   1003,
  "cooperation":    970,
  "group":    963,
  "quality":    962,
  "knowledge":    953,
  "working":    953,
  "including":    951,
  "professional":    946,
  "environment":    936,
  "innovation":    934,
  "technology":    928,
  "environmental":    892,
  "can":    879,
  "regional":    879,
  "across":    856,
  "leading":    850,
  "financial":    848,
  "based":    846,
  "within":    839,
  "use":    819,
  "training":    809,
  "human":    804,
  "one":    794,
  "standards":    789,
  "develop":    788,
  "main":    783,
  "protection":    781,
  "political":    759,
  "together":    759,
  "private":    754,
  "service":    753,
  "providing":    740,
  "technical":    735,
  "independent":    733,
  "scientific":    732,
  "clients":    731,
  "represents":    723,
  "policies":    710,
  "law":    706,
  "promoting":    705,
  "community":    702
  },
  wordsList_goal_one:
  [
  "european",
  "international",
  "members",
  "research",
  "europe",
  "development",
  "public",
  "services",
  "national",
  "social",
  "association",
  "industry",
  "information",
  "business",
  "promote",
  "policy",
  "support",
  "activities",
  "organisations",
  "companies",
  "institutions",
  "global",
  "work",
  "countries",
  "management",
  "world",
  "people",
  "sector",
  "network",
  "interests",
  "well",
  "energy",
  "education",
  "member",
  "issues",
  "mission",
  "sustainable",
  "health",
  "organisation",
  "level",
  "provide",
  "society",
  "market",
  "products",
  "associations",
  "economic",
  "rights",
  "projects",
  "local",
  "trade",
  "company",
  "new",
  "ρ�",
  "union",
  "solutions",
  "π�",
  "σ�",
  "cooperation",
  "group",
  "quality",
  "knowledge",
  "working",
  "including",
  "professional",
  "environment",
  "innovation",
  "technology",
  "environmental",
  "can",
  "regional",
  "across",
  "leading",
  "financial",
  "based",
  "σ�",
  "within",
  "р�",
  "use",
  "training",
  "human",
  "one",
  "standards",
  "develop",
  "main",
  "protection",
  "political",
  "together",
  "private",
  "service",
  "providing",
  "technical",
  "independent",
  "scientific",
  "clients",
  "represents",
  "policies",
  "law",
  "promoting",
  "community",
  ],
  wordCountMapping_activity_one:
  {
  "european":   6760,
  "directive":   6092,
  "policy":   5442,
  "energy":   4210,
  "regulation":   4122,
  "market":   3412,
  "policies":   2286,
  "digital":   2256,
  "development":   2198,
  "protection":   2084,
  "union":   2048,
  "trade":   2028,
  "health":   1978,
  "europe":   1950,
  "social":   1906,
  "research":   1872,
  "initiatives":   1762,
  "strategy":   1752,
  "single":   1748,
  "rights":   1620,
  "data":   1614,
  "legislation":   1512,
  "framework":   1510,
  "commission":   1500,
  "public":   1490,
  "economy":   1484,
  "innovation":   1432,
  "horizon":   1414,
  "services":   1414,
  "related":   1402,
  "transport":   1394,
  "food":   1366,
  "climate":   1364,
  "education":   1344,
  "issues":   1312,
  "financial":   1304,
  "council":   1294,
  "implementation":   1274,
  "safety":   1168,
  "parliament":   1158,
  "environment":   1150,
  "security":   1140,
  "package":   1100,
  "agenda":   1078,
  "international":   1042,
  "activities":   1022,
  "circular":   1000,
  "information":    990,
  "waste":    984,
  "action":    962,
  "work":    952,
  "including":    950,
  "products":    940,
  "programme":    902,
  "ttip":    898,
  "environmental":    878,
  "investment":    866,
  "plan":    862,
  "review":    840,
  "sustainable":    830,
  "markets":    828,
  "copyright":    820,
  "efficiency":    784,
  "initiative":    784,
  "general":    772,
  "law":    770,
  "human":    752,
  "member":    752,
  "new":    746,
  "consumer":    742,
  "sector":    738,
  "following":    728,
  "affairs":    718,
  "areas":    694,
  "capital":    694,
  "legislative":    690,
  "industry":    688,
  "proposal":    686,
  "reach":    680,
  "common":    674,
  "group":    672,
  "consultation":    668,
  "internal":    666,
  "business":    664,
  "access":    662,
  "economic":    662,
  "regulations":    662,
  "institutions":    658,
  "etc":    656,
  "management":    648,
  "change":    636,
  "national":    614,
  "water":    614,
  "working":    608,
  "cooperation":    602,
  "competition":    598,
  "regional":    598,
  "employment":    596,
  "reform":    596,
  "members":    592
  },
  wordsList_activity_one:
  [
  "european",
  "directive",
  "policy",
  "energy",
  "regulation",
  "market",
  "policies",
  "digital",
  "development",
  "protection",
  "union",
  "trade",
  "health",
  "europe",
  "social",
  "research",
  "initiatives",
  "strategy",
  "single",
  "rights",
  "data",
  "legislation",
  "framework",
  "commission",
  "public",
  "economy",
  "innovation",
  "horizon",
  "services",
  "related",
  "transport",
  "food",
  "climate",
  "education",
  "issues",
  "financial",
  "council",
  "implementation",
  "safety",
  "parliament",
  "environment",
  "security",
  "package",
  "agenda",
  "international",
  "activities",
  "circular",
  "information",
  "waste",
  "action",
  "work",
  "including",
  "products",
  "programme",
  "ttip",
  "environmental",
  "investment",
  "plan",
  "review",
  "sustainable",
  "markets",
  "copyright",
  "efficiency",
  "initiative",
  "general",
  "law",
  "human",
  "member",
  "new",
  "consumer",
  "sector",
  "following",
  "affairs",
  "areas",
  "capital",
  "legislative",
  "industry",
  "proposal",
  "reach",
  "common",
  "group",
  "consultation",
  "internal",
  "business",
  "access",
  "economic",
  "regulations",
  "institutions",
  "etc",
  "management",
  "change",
  "national",
  "water",
  "working",
  "cooperation",
  "competition",
  "regional",
  "employment",
  "reform",
  "members"
  ],
  wordCountMapping_both_one:
  {
  "european":   9943,
  "policy":   4576,
  "development":   4130,
  "europe":   4023,
  "international":   4000,
  "research":   3988,
  "energy":   3448,
  "members":   3446,
  "public":   3297,
  "social":   3219,
  "services":   3193,
  "directive":   3124,
  "market":   2899,
  "national":   2709,
  "industry":   2529,
  "information":   2493,
  "association":   2346,
  "business":   2318,
  "regulation":   2286,
  "health":   2258,
  "activities":   2236,
  "europa":   2224,
  "support":   2097,
  "trade":   2077,
  "promote":   2048,
  "union":   2037,
  "work":   1996,
  "education":   1984,
  "institutions":   1968,
  "issues":   1961,
  "rights":   1917,
  "policies":   1853,
  "protection":   1823,
  "organisations":   1812,
  "global":   1781,
  "sector":   1775,
  "management":   1761,
  "companies":   1754,
  "sustainable":   1690,
  "member":   1683,
  "countries":   1682,
  "innovation":   1650,
  "network":   1642,
  "products":   1635,
  "well":   1588,
  "digital":   1585,
  "people":   1564,
  "world":   1514,
  "environment":   1512,
  "level":   1505,
  "financial":   1501,
  "society":   1487,
  "interests":   1468,
  "economic":   1450,
  "including":   1426,
  "data":   1421,
  "organisation":   1408,
  "new":   1396,
  "transport":   1368,
  "related":   1361,
  "projects":   1350,
  "provide":   1344,
  "food":   1336,
  "environmental":   1331,
  "mission":   1328,
  "group":   1299,
  "initiatives":   1294,
  "cooperation":   1271,
  "commission":   1263,
  "working":   1257,
  "economy":   1250,
  "quality":   1234,
  "legislation":   1207,
  "strategy":   1207,
  "local":   1198,
  "associations":   1192,
  "human":   1180,
  "regional":   1178,
  "company":   1150,
  "technology":   1148,
  "safety":   1142,
  "framework":   1130,
  "implementation":   1127,
  "council":   1117,
  "professional":   1111,
  "law":   1091,
  "use":   1085,
  "solutions":   1066,
  "training":   1057,
  "knowledge":   1051,
  "climate":   1050,
  "areas":   1045,
  "security":   1038,
  "within":   1036,
  "main":   1028,
  "general":   1023 
  },
  wordsList_both_one:
  [
  "european",
  "policy",
  "development",
  "europe",
  "international",
  "research",
  "energy",
  "members",
  "public",
  "social",
  "services",
  "directive",
  "market",
  "national",
  "industry",
  "information",
  "association",
  "business",
  "regulation",
  "health",
  "activities",
  "europa",
  "support",
  "trade",
  "promote",
  "union",
  "work",
  "education",
  "institutions",
  "issues",
  "rights",
  "policies",
  "protection",
  "organisations",
  "global",
  "sector",
  "management",
  "companies",
  "sustainable",
  "member",
  "countries",
  "innovation",
  "network",
  "products",
  "well",
  "digital",
  "people",
  "world",
  "environment",
  "level",
  "financial",
  "society",
  "interests",
  "economic",
  "including",
  "data",
  "organisation",
  "new",
  "transport",
  "related",
  "projects",
  "provide",
  "food",
  "environmental",
  "mission",
  "group",
  "initiatives",
  "cooperation",
  "commission",
  "working",
  "economy",
  "quality",
  "legislation",
  "strategy",
  "local",
  "associations",
  "human",
  "regional",
  "company",
  "technology",
  "safety",
  "framework",
  "implementation",
  "council",
  "professional",
  "law",
  "use",
  "solutions",
  "training",
  "knowledge",
  "climate",
  "areas",
  "security",
  "within",
  "main",
  "general" 
  ],
  wordCountMapping_goal_two:
  {
  "european union":   5352,
  "human rights":   3760,
  "civil society":   2712,
  "national international":   2704,
  "european commission":   2464,
  "member states":   2392,
  "european level":   2384,
  "sustainable development":   2240,
  "around world":   2224,
  "public affairs":   2184,
  "european institutions":   2152,
  "across europe":   2080,
  "wide range":   1736,
  "european international":   1624,
  "european countries":   1552,
  "higher education":   1544,
  "international level":   1512,
  "young people":   1512,
  "economic social":   1424,
  "high quality":   1392,
  "public private":   1392,
  "climate change":   1376,
  "research development":   1376,
  "national european":   1296,
  "products services":   1248,
  "member companies":   1240,
  "interests members":   1224,
  "policy makers":   1208,
  "european parliament":   1200,
  "pouvoirs publics":   1184,
  "member organisations":   1144,
  "renewable energy":   1128,
  "national associations":   1104,
  "exchange information":   1072,
  "decision makers":   1040,
  "represent interests":   1040,
  "brings together":   1032,
  "best practice":   1024,
  "best practices":   1024,
  "education training":   1024,
  "trade association":   1024,
  "united nations":   1008,
  "national regional":   1000,
  "financial services":    992,
  "intellectual property":    984,
  "public health":    976,
  "throughout europe":    944,
  "research innovation":    936,
  "common interests":    928,
  "supply chain":    928,
  "energy efficiency":    904,
  "local authorities":    904,
  "represents interests":    880,
  "national level":    872,
  "social economic":    872,
  "quality life":    856,
  "local regional":    848,
  "public authorities":    848,
  "interests european":    840,
  "international organisations":    840,
  "public policy":    832,
  "• promote":    816,
  "private sector":    816,
  "regional national":    816,
  "think tank":    792,
  "local national":    784,
  "members european":    784,
  "scientific research":    752,
  "european national":    744,
  "within european":    744,
  "common interest":    728,
  "natural gas":    728,
  "european association":    720,
  "raise awareness":    720,
  "working groups":    704,
  "education research":    696,
  "health care":    696,
  "institutions european":    696,
  "general public":    688,
  "waste management":    688,
  "united states":    680,
  "decision making":    672,
  "public interest":    672,
  "united kingdom":    672,
  "darüber hinaus":    664,
  "international cooperation":    648,
  "member associations":    648,
  "trade union":    648,
  "economic development":    640,
  "international trade":    640,
  "service providers":    640,
  "international institutions":    632,
  "institutions européennes":    624,
  "middle east":    624,
  "nonprofit association":    624,
  "nonprofit organization":    624,
  "representing interests":    624,
  "value chain":    624,
  "environmental protection":    616,
  "research projects":    616
  },
  wordsList_goal_two:
  [
  "european union",
  "human rights",
  "civil society",
  "national international",
  "european commission",
  "member states",
  "european level",
  "sustainable development",
  "around world",
  "public affairs",
  "european institutions",
  "across europe",
  "wide range",
  "european international",
  "european countries",
  "higher education",
  "international level",
  "young people",
  "economic social",
  "high quality",
  "public private",
  "climate change",
  "research development",
  "national european",
  "products services",
  "member companies",
  "interests members",
  "policy makers",
  "european parliament",
  "pouvoirs publics",
  "member organisations",
  "renewable energy",
  "national associations",
  "exchange information",
  "decision makers",
  "represent interests",
  "brings together",
  "best practice",
  "best practices",
  "education training",
  "trade association",
  "united nations",
  "national regional",
  "financial services",
  "intellectual property",
  "public health",
  "throughout europe",
  "research innovation",
  "common interests",
  "supply chain",
  "energy efficiency",
  "local authorities",
  "represents interests",
  "national level",
  "social economic",
  "quality life",
  "local regional",
  "public authorities",
  "interests european",
  "international organisations",
  "public policy",
  "• promote",
  "private sector",
  "regional national",
  "think tank",
  "local national",
  "members european",
  "scientific research",
  "european national",
  "within european",
  "common interest",
  "natural gas",
  "european association",
  "raise awareness",
  "working groups",
  "education research",
  "health care",
  "institutions european",
  "general public",
  "waste management",
  "united states",
  "decision making",
  "public interest",
  "united kingdom",
  "darüber hinaus",
  "international cooperation",
  "member associations",
  "trade union",
  "economic development",
  "international trade",
  "service providers",
  "international institutions",
  "institutions européennes",
  "middle east",
  "nonprofit association",
  "nonprofit organization",
  "representing interests",
  "value chain",
  "environmental protection",
  "research projects"
  ],
  wordCountMapping_activity_two:
  {
  "single market":   6064,
  "digital single":   4792,
  "european parliament":   4168,
  "circular economy":   3824,
  "data protection":   3808,
  "energy union":   2792,
  "directive ec":   2728,
  "parliament council":   2720,
  "european commission":   2568,
  "energy efficiency":   2208,
  "human rights":   2120,
  "climate change":   2056,
  "internal market":   2008,
  "capital markets":   1880,
  "research innovation":   1800,
  "markets union":   1688,
  "financial services":   1576,
  "digital agenda":   1552,
  "action plan":   1520,
  "framework directive":   1480,
  "european union":   1440,
  "protection regulation":   1336,
  "initiatives policies":   1320,
  "renewable energy":   1232,
  "regulation european":   1208,
  "climate energy":   1168,
  "regulation ec":   1144,
  "raw materials":   1128,
  "legislative files":   1080,
  "public consultation":   1072,
  "food safety":   1064,
  "intellectual property":   1064,
  "public procurement":   1064,
  "member states":   1056,
  "energy climate":   1048,
  "sustainable development":   1024,
  "energy policy":   1016,
  "directive european":   1008,
  "economy package":   1008,
  "market strategy":    984,
  "public health":    928,
  "trade policy":    928,
  "medical devices":    920,
  "policies legislative":    920,
  "civil society":    912,
  "general data":    832,
  "industrial policy":    824,
  "state aid":    824,
  "trade investment":    824,
  "proposal regulation":    816,
  "directive energy":    784,
  "higher education":    768,
  "consumer protection":    760,
  "rural development":    744,
  "better regulation":    736,
  "efficiency directive":    688,
  "policy areas":    680,
  "services directive":    672,
  "water framework":    672,
  "education training":    664,
  "agricultural policy":    648,
  "proposal directive":    648,
  "resource efficiency":    640,
  "mifid ii":    632,
  "trade agreements":    632,
  "commission european":    624,
  "solvency ii":    608,
  "transatlantic trade":    608,
  "european innovation":    600,
  "audiovisual media":    592,
  "employment social":    592,
  "investment partnership":    584,
  "working group":    584,
  "financial instruments":    576,
  "corporate governance":    568,
  "energy market":    568,
  "creative europe":    560,
  "market surveillance":    552,
  "air quality":    544,
  "market design":    544,
  "medicinal products":    544,
  "regional policy":    536,
  "competition policy":    528,
  "amending directive":    520,
  "clinical trials":    520,
  "ec european":    520,
  "energy directive":    520,
  "investment plan":    520,
  "social affairs":    520,
  "energy performance":    512,
  "health safety":    512,
  "international trade":    512,
  "policy energy":    504,
  "common agricultural":    496,
  "copyright reform":    496,
  "council directive":    496,
  "policy european":    496,
  "supply chain":    496,
  "free movement":    488,
  "fundamental rights":    488 
  },
  wordsList_activity_two:
  [
  "single market",
  "digital single",
  "european parliament",
  "circular economy",
  "data protection",
  "energy union",
  "directive ec",
  "parliament council",
  "european commission",
  "energy efficiency",
  "human rights",
  "climate change",
  "internal market",
  "capital markets",
  "research innovation",
  "markets union",
  "financial services",
  "digital agenda",
  "action plan",
  "framework directive",
  "european union",
  "protection regulation",
  "initiatives policies",
  "renewable energy",
  "regulation european",
  "climate energy",
  "regulation ec",
  "raw materials",
  "legislative files",
  "public consultation",
  "food safety",
  "intellectual property",
  "public procurement",
  "member states",
  "energy climate",
  "sustainable development",
  "energy policy",
  "directive european",
  "economy package",
  "market strategy",
  "public health",
  "trade policy",
  "medical devices",
  "policies legislative",
  "civil society",
  "general data",
  "industrial policy",
  "state aid",
  "trade investment",
  "proposal regulation",
  "directive energy",
  "higher education",
  "consumer protection",
  "rural development",
  "better regulation",
  "efficiency directive",
  "policy areas",
  "services directive",
  "water framework",
  "education training",
  "agricultural policy",
  "proposal directive",
  "resource efficiency",
  "mifid ii",
  "trade agreements",
  "commission european",
  "solvency ii",
  "transatlantic trade",
  "european innovation",
  "audiovisual media",
  "employment social",
  "investment partnership",
  "working group",
  "financial instruments",
  "corporate governance",
  "energy market",
  "creative europe",
  "market surveillance",
  "air quality",
  "market design",
  "medicinal products",
  "regional policy",
  "competition policy",
  "amending directive",
  "clinical trials",
  "ec european",
  "energy directive",
  "investment plan",
  "social affairs",
  "energy performance",
  "health safety",
  "international trade",
  "policy energy",
  "common agricultural",
  "copyright reform",
  "council directive",
  "policy european",
  "supply chain",
  "free movement",
  "fundamental rights"
  ],
  wordCountMapping_both_two:
  {
  "european union":   6792,
  "single market":   6280,
  "human rights":   5880,
  "european parliament":   5368,
  "european commission":   5032,
  "digital single":   4864,
  "data protection":   4168,
  "circular economy":   4104,
  "civil society":   3624,
  "member states":   3448,
  "climate change":   3432,
  "sustainable development":   3264,
  "energy efficiency":   3112,
  "national international":   2896,
  "parliament council":   2888,
  "energy union":   2800,
  "european level":   2792,
  "directive ec":   2768,
  "research innovation":   2736,
  "financial services":   2568,
  "european institutions":   2464,
  "public affairs":   2368,
  "renewable energy":   2360,
  "across europe":   2312,
  "around world":   2312,
  "higher education":   2312,
  "capital markets":   2232,
  "internal market":   2152,
  "intellectual property":   2048,
  "wide range":   2000,
  "public health":   1904,
  "young people":   1896,
  "economic social":   1880,
  "research development":   1816,
  "european countries":   1736,
  "european international":   1728,
  "raw materials":   1728,
  "education training":   1688,
  "markets union":   1688,
  "action plan":   1632,
  "international level":   1632,
  "digital agenda":   1624,
  "public private":   1544,
  "framework directive":   1496,
  "high quality":   1464,
  "policy makers":   1456,
  "food safety":   1424,
  "national european":   1424,
  "supply chain":   1424,
  "products services":   1416,
  "protection regulation":   1368,
  "initiatives policies":   1352,
  "rural development":   1320,
  "public procurement":   1296,
  "interests members":   1288,
  "member companies":   1288,
  "climate energy":   1264,
  "energy climate":   1264,
  "medical devices":   1232,
  "regulation european":   1232,
  "commission european":   1216,
  "member organisations":   1208,
  "exchange information":   1192,
  "pouvoirs publics":   1192,
  "best practices":   1176,
  "energy policy":   1168,
  "regulation ec":   1168,
  "international trade":   1152,
  "national associations":   1152,
  "united nations":   1144,
  "best practice":   1128,
  "trade investment":   1128,
  "health safety":   1104,
  "decision makers":   1096,
  "legislative files":   1096,
  "brings together":   1088,
  "national regional":   1088,
  "public consultation":   1080,
  "trade association":   1072,
  "national level":   1064,
  "represent interests":   1056,
  "trade policy":   1056,
  "members european":   1040,
  "local authorities":   1032,
  "throughout europe":   1024,
  "animal welfare":   1016,
  "directive european":   1016,
  "economy package":   1008,
  "private sector":   1008,
  "working groups":   1000,
  "common interests":    984,
  "european research":    984,
  "market strategy":    984,
  "health care":    976,
  "social economic":    976,
  "public policy":    968,
  "waste management":    960,
  "consumer protection":    944,
  "policies legislative":    944,
  "represents interests":    944
  },
  wordsList_both_two:
  [
  "european union",
  "single market",
  "human rights",
  "european parliament",
  "european commission",
  "digital single",
  "data protection",
  "circular economy",
  "civil society",
  "member states",
  "climate change",
  "sustainable development",
  "energy efficiency",
  "national international",
  "parliament council",
  "energy union",
  "european level",
  "directive ec",
  "research innovation",
  "financial services",
  "european institutions",
  "public affairs",
  "renewable energy",
  "across europe",
  "around world",
  "higher education",
  "capital markets",
  "internal market",
  "intellectual property",
  "wide range",
  "public health",
  "young people",
  "economic social",
  "research development",
  "european countries",
  "european international",
  "raw materials",
  "education training",
  "markets union",
  "action plan",
  "international level",
  "digital agenda",
  "public private",
  "framework directive",
  "high quality",
  "policy makers",
  "food safety",
  "national european",
  "supply chain",
  "products services",
  "protection regulation",
  "initiatives policies",
  "rural development",
  "public procurement",
  "interests members",
  "member companies",
  "climate energy",
  "energy climate",
  "medical devices",
  "regulation european",
  "commission european",
  "member organisations",
  "exchange information",
  "pouvoirs publics",
  "best practices",
  "energy policy",
  "regulation ec",
  "international trade",
  "national associations",
  "united nations",
  "best practice",
  "trade investment",
  "health safety",
  "decision makers",
  "legislative files",
  "brings together",
  "national regional",
  "public consultation",
  "trade association",
  "national level",
  "represent interests",
  "trade policy",
  "members european",
  "local authorities",
  "throughout europe",
  "animal welfare",
  "directive european",
  "economy package",
  "private sector",
  "working groups",
  "common interests",
  "european research",
  "market strategy",
  "health care",
  "social economic",
  "public policy",
  "waste management",
  "consumer protection",
  "policies legislative",
  "represents interests" 
  ]
}